'use strict';
const $=s=>document.querySelector(s), categories=['본예산','추경예산','결산','사업명세서','기금','검토보고서'];
const fields=['base','final','spent','carry','unused'];let db,docs=[],records=[],category=0,year=new Date().getFullYear(),timer;
const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const format=v=>v==null?'—':Number(v).toLocaleString('ko-KR',{maximumFractionDigits:3});
const safeURL=v=>{try{const u=new URL(v);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
function notice(t){$('#status').textContent=t;$('#status').classList.add('status-show');clearTimeout(timer);timer=setTimeout(()=>$('#status').classList.remove('status-show'),5500)}
function transact(store,mode,action){return new Promise((resolve,reject)=>{const tx=db.transaction(store,mode);let result;try{const req=action(tx.objectStore(store));if(req)req.onsuccess=()=>result=req.result}catch(e){reject(e);return}tx.oncomplete=()=>resolve(result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)})}
const save=(store,obj)=>transact(store,'readwrite',s=>s.put(obj));const remove=(store,id)=>transact(store,'readwrite',s=>s.delete(id));
async function load(){[docs,records]=await Promise.all(['docs','records'].map(s=>transact(s,'readonly',o=>o.getAll())));render()}
function render(){const years=[year-2,year-1,year];$('#range').textContent=`${year-2} — ${year} / 3개년 자료`;$('#docCount').textContent=`등록 자료 ${docs.filter(d=>years.includes(d.year)).length}건`;$('#folders').innerHTML=categories.map((c,i)=>`<a class="folder" href="#folder/${i}" data-category="${i}" aria-label="${c} 자료 페이지"><span class="folder-index">0${i+1}</span><span class="folder-paper"><strong>${c}</strong><small>${docs.filter(d=>d.category===i&&years.includes(d.year)).length}개 자료</small></span><span class="pocket" aria-hidden="true"></span></a>`).join('');$('#folderTitle').textContent=categories[category];const previous=$('#docYear').value;$('#docYear').innerHTML='<option value="all">3개년 전체</option>'+years.map(y=>`<option>${y}</option>`).join('');$('#docYear').value=years.includes(Number(previous))?previous:'all';renderDocs();renderComparison();applyRoute()}
function renderDocs(){const filter=$('#search').value.toLowerCase(), chosen=$('#docYear').value;const list=docs.filter(d=>d.category===category&&d.year>=year-2&&d.year<=year&&(chosen==='all'||d.year===Number(chosen))&&`${d.title} ${d.dept}`.toLowerCase().includes(filter)).sort((a,b)=>b.year-a.year||a.title.localeCompare(b.title,'ko'));$('#documents').innerHTML=list.length?list.map(d=>`<article class="doc"><div><h3>${escapeHTML(d.title)}</h3><div class="meta">${d.year} · ${escapeHTML(d.dept||'부서 미기입')}${d.file?' · '+escapeHTML(d.file.name):''}</div>${d.note?`<p class="meta">${escapeHTML(d.note)}</p>`:''}</div><div class="actions">${d.file?`<button data-open="${d.id}">파일 열기</button>`:''}${safeURL(d.url)?`<a class="link" href="${escapeHTML(safeURL(d.url))}" target="_blank" rel="noopener noreferrer">출처 원문</a>`:''}<button data-delete-doc="${d.id}" class="detail-button">삭제</button></div></article>`).join(''):'<div class="empty">등록된 자료가 없습니다.<br>해당 연도의 원문 자료를 등록해 주십시오.</div>'}
function renderComparison(){const metric=$('#metric').value,filter=$('#projectSearch').value.toLowerCase();const groups=new Map();records.filter(r=>r.year>=year-2&&r.year<=year).forEach(r=>{const key=JSON.stringify([r.code,r.dept,r.account]);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r)});$('#comparisonHead').innerHTML=`<tr><th>사업 / 회계</th><th>${year-2} (t−2)</th><th>${year-1} (t−1)</th><th>${year} (t)</th><th>t−1 대비 증감률</th><th>t 집행률</th><th>근거 / 수정</th></tr>`;let html='';for(const group of groups.values()){const latest=[...group].sort((a,b)=>b.year-a.year)[0];if(!`${latest.name} ${latest.dept}`.toLowerCase().includes(filter))continue;const rows=[year-2,year-1,year].map(y=>group.find(r=>r.year===y));const a=rows[1]?.[metric],b=rows[2]?.[metric],rate=a!=null&&b!=null&&a!==0?(b-a)/a*100:null;const t=rows[2],execution=t?.spent!=null&&t?.final>0?t.spent/t.final*100:null;html+=`<tr><td>${escapeHTML(latest.name)}<small>${escapeHTML(latest.dept)} · ${escapeHTML(latest.account)}<br>${escapeHTML(latest.code)}</small></td>${rows.map(r=>`<td>${format(r?.[metric])}</td>`).join('')}<td class="${rate>0?'positive':rate<0?'negative':''}">${rate==null?'—':(rate>0?'+':'')+rate.toFixed(1)+'%'}</td><td>${execution==null?'—':execution.toFixed(1)+'%'}</td><td>${rows.filter(Boolean).map(r=>`<button class="detail-button" data-edit="${r.id}">${r.year}</button>`).join(' ')}</td></tr>`}$('#comparison').innerHTML=html||'<tr><td colspan="7"><div class="empty">사업 수치를 입력하면 3개년 비교 결과가 표시됩니다.<br>미등록 연도는 “—”로 표시됩니다.</div></td></tr>'}
function fillSources(selected=''){ $('#source').innerHTML='<option value="">근거 자료를 선택해 주십시오</option>'+docs.map(d=>`<option value="${d.id}">${d.year} · ${escapeHTML(d.title)}</option>`).join('');$('#source').value=selected;$('#source').required=true }
function openRecord(r){const f=$('#recordForm');f.reset();fillSources(r?.source);f.elements.year.value=year;if(r){for(const k of ['id','code','name','dept','account','year',...fields,'source','page','note'])f.elements[k].value=r[k]??''}$('#recordDialog').showModal()}
$('#year').innerHTML=Array.from({length:101},(_,i)=>2000+i).map(y=>`<option ${y===year?'selected':''}>${y}</option>`).join('');$('#category').innerHTML=categories.map((c,i)=>`<option value="${i}">${c}</option>`).join('');
$('#year').onchange=()=>{year=Number($('#year').value);render()};
$('#docYear').onchange=renderDocs;$('#search').oninput=renderDocs;$('#metric').onchange=renderComparison;$('#projectSearch').oninput=renderComparison;
$('#addDoc').onclick=()=>{$('#docForm').reset();$('#docForm').elements.year.value=year;$('#category').value=category;$('#docDialog').showModal()};$('#addRecord').onclick=()=>{if(!docs.length)return notice('근거로 사용할 원문 자료를 먼저 등록해 주십시오.');openRecord()};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#docForm').onsubmit=async e=>{e.preventDefault();const f=e.target,fd=new FormData(f),file=f.elements.file.files[0];if(!file&&!fd.get('url'))return notice('파일 또는 출처 URL을 등록해 주십시오.');if(fd.get('url')&&!safeURL(fd.get('url')))return notice('http 또는 https 출처 주소를 입력해 주십시오.');const item={id:crypto.randomUUID(),title:fd.get('title').trim(),year:Number(fd.get('year')),category:Number(fd.get('category')),dept:fd.get('dept').trim(),url:fd.get('url'),note:fd.get('note'),file:file||null};try{await save('docs',item);$('#docDialog').close();await load();notice('자료를 기기 내에 저장하였습니다.')}catch{notice('저장에 실패하였습니다. 브라우저 저장 공간과 권한을 확인해 주십시오.')}};
$('#recordForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),item={id:fd.get('id')||crypto.randomUUID()};for(const k of ['code','name','dept','account','source','page','note'])item[k]=fd.get(k).trim();item.year=Number(fd.get('year'));for(const k of fields)item[k]=fd.get(k)===''?null:Number(fd.get(k));if(!docs.some(d=>d.id===item.source))return notice('등록된 근거 자료를 선택해 주십시오.');if(records.some(r=>r.id!==item.id&&r.code===item.code&&r.dept===item.dept&&r.account===item.account&&r.year===item.year))return notice('같은 사업·부서·회계·연도의 기록이 있습니다. 기존 기록을 수정해 주십시오.');try{await save('records',item);$('#recordDialog').close();await load();notice('사업 수치를 저장하였습니다.')}catch{notice('사업 수치 저장에 실패하였습니다.')}};
$('#documents').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.open){const d=docs.find(d=>d.id===b.dataset.open);const url=URL.createObjectURL(d.file);const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';if(!/\.pdf$/i.test(d.file.name))a.download=d.file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}if(b.dataset.deleteDoc){if(records.some(r=>r.source===b.dataset.deleteDoc))return notice('사업 수치의 근거로 연결된 자료입니다. 해당 수치의 근거를 먼저 변경해 주십시오.');if(confirm('이 자료와 첨부 파일을 삭제하시겠습니까?')){try{await remove('docs',b.dataset.deleteDoc);await load()}catch{notice('삭제에 실패하였습니다.')}}}};
$('#comparison').onclick=e=>{const b=e.target.closest('[data-edit]');if(b)openRecord(records.find(r=>r.id===b.dataset.edit))};
const blobData=blob=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(blob)});
$('#backup').onclick=async()=>{try{const data={version:1,exportedAt:new Date().toISOString(),docs:await Promise.all(docs.map(async d=>({...d,file:d.file?{name:d.file.name,type:d.file.type,data:await blobData(d.file)}:null}))),records};const url=URL.createObjectURL(new Blob([JSON.stringify(data)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`haeundae-budget-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);notice('첨부 파일을 포함한 백업을 다운로드하였습니다.')}catch{notice('백업에 실패하였습니다. 저장 공간과 파일 크기를 확인해 주십시오.')}};
function validateBackup(data){if(data.version!==1||!Array.isArray(data.docs)||!Array.isArray(data.records))throw Error('format');const ids=new Set();for(const d of data.docs){if(typeof d.id!=='string'||ids.has(d.id)||typeof d.title!=='string'||typeof d.dept!=='string'||typeof d.note!=='string'||!Number.isInteger(d.year)||d.year<2000||d.year>2100||!Number.isInteger(d.category)||d.category<0||d.category>5||typeof d.url!=='string'||(d.url&&!safeURL(d.url)))throw Error('doc');ids.add(d.id);if(d.file&&(typeof d.file.name!=='string'||typeof d.file.type!=='string'||typeof d.file.data!=='string'||!/^data:[^,]*;base64,[A-Za-z0-9+/=]*$/.test(d.file.data)))throw Error('file')}const keys=new Set(),recordIds=new Set();for(const r of data.records){if(typeof r.id!=='string'||recordIds.has(r.id)||!['code','name','dept','account','source','page','note'].every(k=>typeof r[k]==='string')||!ids.has(r.source)||!Number.isInteger(r.year)||r.year<2000||r.year>2100||fields.some(k=>r[k]!==null&&(typeof r[k]!=='number'||!Number.isFinite(r[k])||r[k]<0)))throw Error('record');recordIds.add(r.id);const key=JSON.stringify([r.code,r.dept,r.account,r.year]);if(keys.has(key))throw Error('duplicate');keys.add(key)}}
$('#restore').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());validateBackup(data);const restored=data.docs.map(d=>{if(!d.file)return d;const content=atob(d.file.data.split(',')[1]);const bytes=Uint8Array.from(content,c=>c.charCodeAt(0));return {...d,file:new File([bytes],d.file.name,{type:d.file.type})}});if(!confirm('현재 자료를 백업 내용으로 교체합니다. 기존 자료를 먼저 백업하셨습니까?'))return;await new Promise((resolve,reject)=>{const tx=db.transaction(['docs','records'],'readwrite');for(const name of ['docs','records'])tx.objectStore(name).clear();restored.forEach(d=>tx.objectStore('docs').put(d));data.records.forEach(r=>tx.objectStore('records').put(r));tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});await load();notice('백업을 복원하였습니다.')}catch{notice('복원에 실패하였습니다. 백업 형식 또는 저장 공간을 확인해 주십시오.')}finally{e.target.value=''}};
const request=indexedDB.open('haeundae-budget-private',1);request.onupgradeneeded=()=>{for(const s of ['docs','records'])request.result.createObjectStore(s,{keyPath:'id'})};request.onsuccess=async()=>{db=request.result;try{await load()}catch{notice('자료를 읽지 못하였습니다. 브라우저 권한을 확인해 주십시오.')}};request.onerror=()=>notice('브라우저 저장소를 열 수 없습니다. 일반 브라우저 모드에서 실행해 주십시오.');

function applyRoute(){
 const match=location.hash.match(/^#folder\/([0-5])$/);const compare=location.hash==='#comparison';
 $('#libraryHome').hidden=Boolean(match)||compare;$('#documentPage').hidden=!match;$('#comparisonPage').hidden=!compare;
 if(match){category=Number(match[1]);$('#folderTitle').textContent=categories[category];$('#pageCategory').textContent=categories[category];renderDocs();document.title=categories[category]+' · 해운대구 예·결산 분석 프로그램'}else{document.title=compare?'3개년 비교 · 해운대구 예·결산 분석 프로그램':'해운대구 예·결산 분석 프로그램'}
}
window.addEventListener('hashchange',()=>{$('#search').value='';applyRoute();window.scrollTo({top:0,behavior:'instant'});});
applyRoute();


